/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gadgetrepair.frames;
import gadgetrepair.data.DatabaseConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class ForgotPasswordFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ForgotPasswordFrame.class.getName());
    private String verifiedUsername = null;

    /**
     * Creates new form ForgotPasswordFrame
     */
    public ForgotPasswordFrame() {
        initComponents();
        cmbSecurityQuestion.setEnabled(false);

        txtNewPassword.setEnabled(false);
        txtConfirmPassword.setEnabled(false);
        btnSave.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTitle = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnVerify = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbSecurityQuestion = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtSecurityAnswer = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtNewPassword = new javax.swing.JPasswordField();
        txtConfirmPassword = new javax.swing.JPasswordField();
        chkShowNewPassword = new javax.swing.JCheckBox();
        chkShowConfirmPassword = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(18, 52, 86));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 80));

        txtTitle.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(242, 242, 242));
        txtTitle.setText("FORGOT PASSWORD");
        txtTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\LOGO REPAIRsss.png")); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(135, 135));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addComponent(txtTitle)
                .addGap(131, 131, 131)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTitle)
                .addGap(34, 34, 34))
        );

        jLabel1.setText("Username:");

        btnVerify.setText("VERIFY");
        btnVerify.addActionListener(this::btnVerifyActionPerformed);

        jLabel2.setText("Security Question:");

        cmbSecurityQuestion.setEditable(true);
        cmbSecurityQuestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Security Question", "What is your favorite color?", "What is the name of your first pet?", "What is your favorite food?", "What city were you born in?", "What is your favorite movie?" }));

        jLabel3.setText("Answer:");

        jLabel4.setText("New Password:");

        jLabel5.setText("Confirm Password:");

        btnSave.setBackground(new java.awt.Color(24, 91, 160));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("SAVE");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        btnBack.setBackground(new java.awt.Color(24, 91, 160));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.addActionListener(this::btnBackActionPerformed);

        chkShowNewPassword.setText("Show Password");
        chkShowNewPassword.addActionListener(this::chkShowNewPasswordActionPerformed);

        chkShowConfirmPassword.setText("Show Password");
        chkShowConfirmPassword.addActionListener(this::chkShowConfirmPasswordActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(73, 73, 73)
                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(123, 123, 123))
                                    .addComponent(txtNewPassword)
                                    .addComponent(txtSecurityAnswer)
                                    .addComponent(txtConfirmPassword)
                                    .addComponent(cmbSecurityQuestion, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkShowNewPassword)
                            .addComponent(chkShowConfirmPassword)
                            .addComponent(btnVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerify))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbSecurityQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSecurityAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkShowNewPassword))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(chkShowConfirmPassword))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnSave))
                .addGap(0, 42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyActionPerformed

 String username = txtUsername.getText().trim();

        if (username.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please enter your username."
            );

            return;
        }

        String sql =
                "SELECT security_question " +
                "FROM accounts " +
                "WHERE username = ? AND is_active = 1";

        try (
                Connection conn = DatabaseConnection.getConnection();
                PreparedStatement pst = conn.prepareStatement(sql)
        ) {

            pst.setString(1, username);

            try (ResultSet rs = pst.executeQuery()) {

                if (rs.next()) {

                    String question =
                            rs.getString("security_question");

                    // Load the saved question
                    cmbSecurityQuestion.removeAllItems();
                    cmbSecurityQuestion.addItem(question);

                    // Prevent changing the question
                    cmbSecurityQuestion.setEnabled(false);

                    // Remember the verified username
                    verifiedUsername = username;

                    // Enable password fields
                    txtNewPassword.setEnabled(true);
                    txtConfirmPassword.setEnabled(true);
                    btnSave.setEnabled(true);

                    JOptionPane.showMessageDialog(
                            this,
                            "Username found. Please answer your security question."
                    );

                } else {

                    verifiedUsername = null;

                    JOptionPane.showMessageDialog(
                            this,
                            "Username not found."
                    );
                }
            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Database error:\n" + e.getMessage()
            );
        }
    
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerifyActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
    String username = txtUsername.getText().trim();
    String question = cmbSecurityQuestion.getSelectedItem().toString();
    String answer = txtSecurityAnswer.getText().trim();
    String newPassword = new String(txtNewPassword.getPassword());
    String confirmPassword = new String(txtConfirmPassword.getPassword());

    // ===== CHECK EMPTY FIELDS =====
    if (username.isEmpty() ||
        answer.isEmpty() ||
        newPassword.isEmpty() ||
        confirmPassword.isEmpty()) {

        JOptionPane.showMessageDialog(
            this,
            "Please complete all fields."
        );
        return;
    }

    // ===== CHECK PASSWORD MATCH =====
    if (!newPassword.equals(confirmPassword)) {

        JOptionPane.showMessageDialog(
            this,
            "Passwords do not match."
        );
        return;
    }

    // ===== PASSWORD REQUIREMENTS =====
    if (!newPassword.matches(
            "^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@#$%^&+=!]).{8,}$")) {

        JOptionPane.showMessageDialog(
            this,
            "Password must contain:\n" +
            "• At least 8 characters\n" +
            "• At least 1 letter\n" +
            "• At least 1 number\n" +
            "• At least 1 special character"
        );
        return;
    }

    // ===== VERIFY SECURITY ANSWER =====
    String checkSQL =
        "SELECT * FROM accounts " +
        "WHERE username = ? " +
        "AND security_question = ? " +
        "AND security_answer = ? " +
        "AND is_active = 1";

    try (
        Connection conn = DatabaseConnection.getConnection();
        PreparedStatement checkPst =
            conn.prepareStatement(checkSQL)
    ) {

        checkPst.setString(1, username);
        checkPst.setString(2, question);
        checkPst.setString(3, answer);

        try (ResultSet rs = checkPst.executeQuery()) {

            if (!rs.next()) {

                JOptionPane.showMessageDialog(
                    this,
                    "Incorrect security answer."
                );
                return;
            }
        }

        // ===== UPDATE PASSWORD =====
        String updateSQL =
            "UPDATE accounts SET password = ? " +
            "WHERE username = ? AND is_active = 1";

        try (PreparedStatement updatePst =
                 conn.prepareStatement(updateSQL)) {

            updatePst.setString(1, newPassword);
            updatePst.setString(2, username);

            updatePst.executeUpdate();
        }

        // ===== SUCCESS MESSAGE =====
        JOptionPane.showMessageDialog(
            this,
            "Password reset successfully."
        );

        // ===== RETURN TO LOGIN =====
        new Loginframee().setVisible(true);
        this.dispose();

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
            this,
            "Error resetting password:\n" + e.getMessage()
        );
    }
    // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void chkShowNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowNewPasswordActionPerformed
      if (chkShowNewPassword.isSelected()) {
        txtNewPassword.setEchoChar((char) 0);
    } else {
        txtNewPassword.setEchoChar('•');
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_chkShowNewPasswordActionPerformed

    private void chkShowConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowConfirmPasswordActionPerformed
   if (chkShowConfirmPassword.isSelected()) {
        txtConfirmPassword.setEchoChar((char) 0);
    } else {
        txtConfirmPassword.setEchoChar('•');
    }        // TODO add your handling code here:
    }//GEN-LAST:event_chkShowConfirmPasswordActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new Loginframee().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ForgotPasswordFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnVerify;
    private javax.swing.JCheckBox chkShowConfirmPassword;
    private javax.swing.JCheckBox chkShowNewPassword;
    private javax.swing.JComboBox<String> cmbSecurityQuestion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JTextField txtSecurityAnswer;
    private javax.swing.JLabel txtTitle;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
