/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gadgetrepair.frames.technician;
import javax.swing.JOptionPane;
import gadgetrepair.data.DatabaseConnection;
import gadgetrepair.frames.Loginframee;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class TechnicianDashboard extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TechnicianDashboard.class.getName());
private int technicianId;
private String technicianUsername;
   private void loadRepairs() {

    String sql =
        "SELECT " +
        "r.repair_id, " +
        "CONCAT(c.first_name, ' ', c.last_name) AS customer, " +
        "CONCAT(g.brand_model, ' - ', g.gadget_type) AS gadget, " +
        "r.repair_description AS problem, " +
        "a.username AS technician, " +
        "r.date_brought, " +
        "r.repair_status " +
        "FROM repairs r " +
        "JOIN gadgets g ON r.gadget_id = g.gadget_id " +
        "JOIN customers c ON g.customer_id = c.customer_id " +
        "LEFT JOIN technicians t ON r.technician_id = t.technician_id " +
        "LEFT JOIN accounts a ON t.account_id = a.account_id " +
        "WHERE r.technician_id = ? " +
        "AND r.is_archived = 0 " +
        "ORDER BY r.repair_id DESC";

    try (
        Connection conn = DatabaseConnection.getConnection();
        PreparedStatement pst = conn.prepareStatement(sql)
    ) {

        pst.setInt(1, technicianId);

        try (ResultSet rs = pst.executeQuery()) {

            DefaultTableModel model =
                (DefaultTableModel) tblRepairs.getModel();

            model.setRowCount(0);

            while (rs.next()) {

                model.addRow(new Object[]{
                    rs.getInt("repair_id"),
                    rs.getString("customer"),
                    rs.getString("gadget"),
                    rs.getString("problem"),
                    rs.getString("technician"),
                    rs.getDate("date_brought"),
                    rs.getString("repair_status")
                });
            }
        }

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
            this,
            "Error loading repairs:\n" + e.getMessage(),
            "Database Error",
            JOptionPane.ERROR_MESSAGE
        );
    }
}

   public TechnicianDashboard(int technicianId, String technicianUsername) {

    initComponents();

    this.technicianId = technicianId;
    this.technicianUsername = technicianUsername;

    lblGreeting.setText("Hello, " + technicianUsername);

    tblRepairs.setDefaultEditor(Object.class, null);

    loadRepairs();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRepairs = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtSearchRepair = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        Technician1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Technician2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblGreeting = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(248, 250, 252));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(18, 52, 86));
        jPanel2.setPreferredSize(new java.awt.Dimension(850, 80));

        txtTitle.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(255, 255, 255));
        txtTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitle.setText("TECHNICIAN DASHBOARD");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\LOGO REPAIRsss.png")); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(135, 135));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(515, Short.MAX_VALUE)
                .addComponent(txtTitle)
                .addGap(375, 375, 375)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1470, 115));

        jButton2.setBackground(new java.awt.Color(220, 53, 69));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("LOGOUT");
        jButton2.setPreferredSize(new java.awt.Dimension(110, 38));
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 150, -1, -1));

        tblRepairs.setBackground(new java.awt.Color(15, 43, 77));
        tblRepairs.setForeground(new java.awt.Color(255, 255, 255));
        tblRepairs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "REPAIR ID", "CUSTOMER", "GADGET", "PROBLEM", "REPAIR TECHNICIAN", "DATE BROUGHT", "Status"
            }
        ));
        tblRepairs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRepairsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRepairs);

        jScrollPane2.setViewportView(jScrollPane1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 900, 390));

        jLabel5.setText("SEARCH REPAIR:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));

        txtSearchRepair.addActionListener(this::txtSearchRepairActionPerformed);
        getContentPane().add(txtSearchRepair, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 90, -1));

        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(this::btnSearchActionPerformed);
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 160, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Repair ID:");

        jLabel6.setBackground(new java.awt.Color(0, 153, 204));
        jLabel6.setText("-");

        jLabel7.setText("Customer");

        jLabel8.setText("-");

        jLabel9.setText("Gadget");

        jLabel10.setText("-");

        jLabel11.setText("Problem:");

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        Technician1.setText("Repair Technician:");

        jLabel15.setText("-");

        Technician2.setText("Date Brought");

        jLabel16.setText("-");

        jLabel13.setText("Status:");

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Status", "Pending", "In Progress", "Completed" }));

        jButton3.setText("SAVE STATUS");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel9))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 220, Short.MAX_VALUE)))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Technician1)
                                    .addComponent(Technician2)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jButton3)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Technician1)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Technician2)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 490, 390));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(18, 52, 86));
        jLabel3.setText("REPAIR DETAILS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        lblGreeting.setText("jLabel2");
        getContentPane().add(lblGreeting, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
int confirm = JOptionPane.showConfirmDialog(
    this,
    "Are you sure you want to logout?",
    "Confirm Logout",
    JOptionPane.YES_NO_OPTION
);

if (confirm == JOptionPane.YES_OPTION) {
    new Loginframee().setVisible(true);
    this.dispose();
}            // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtSearchRepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchRepairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchRepairActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
int row = tblRepairs.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(
            this,
            "Please select a repair first."
        );
        return;
    }

    if (cmbStatus.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(
            this,
            "Please select a status."
        );
        return;
    }

    int repairId = Integer.parseInt(
        tblRepairs.getValueAt(row, 0).toString()
    );

    String status =
        cmbStatus.getSelectedItem().toString();

   String sql =
    "UPDATE repairs " +
    "SET repair_status = ? " +
    "WHERE repair_id = ? " +
    "AND technician_id = ? " +
    "AND is_archived = 0";

    try (
        Connection conn = DatabaseConnection.getConnection();
        PreparedStatement pst = conn.prepareStatement(sql)
    ) {

           pst.setString(1, status);
           pst.setInt(2, repairId);
           pst.setInt(3, technicianId);

        int updated = pst.executeUpdate();

        if (updated > 0) {

            JOptionPane.showMessageDialog(
                this,
                "Repair status updated successfully!"
            );

            loadRepairs();

            jLabel6.setText("-");
            jLabel8.setText("-");
            jLabel10.setText("-");
            jTextArea2.setText("-");
            jLabel15.setText("-");
            jLabel16.setText("-");
            cmbStatus.setSelectedIndex(0);

        } else {

            JOptionPane.showMessageDialog(
                this,
                "No repair was updated."
            );
        }

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
            this,
            "Error updating repair status:\n" + e.getMessage()
        );
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tblRepairsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRepairsMouseClicked
      int row = tblRepairs.getSelectedRow();

    if (row < 0) {
        return;
    }

    jLabel6.setText(
        tblRepairs.getValueAt(row, 0).toString()
    );

    jLabel8.setText(
        tblRepairs.getValueAt(row, 1).toString()
    );

    jLabel10.setText(
        tblRepairs.getValueAt(row, 2).toString()
    );

    jTextArea2.setText(
        tblRepairs.getValueAt(row, 3).toString()
    );

    jLabel15.setText(
        tblRepairs.getValueAt(row, 4).toString()
    );

    jLabel16.setText(
        tblRepairs.getValueAt(row, 5).toString()
    );

    cmbStatus.setSelectedItem(
        tblRepairs.getValueAt(row, 6).toString()
    );
    // TODO add your handling code here:
    }//GEN-LAST:event_tblRepairsMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
 String search = txtSearchRepair.getText().trim();

    if (search.isEmpty()) {

        JOptionPane.showMessageDialog(
            this,
            "Please enter a customer name, gadget, or problem."
        );

        loadRepairs();
        return;
    }

    DefaultTableModel model =
        (DefaultTableModel) tblRepairs.getModel();

    model.setRowCount(0);

    String sql =
        "SELECT " +
        "r.repair_id, " +
        "CONCAT(c.first_name, ' ', c.last_name) AS customer_name, " +
        "CONCAT(g.brand_model, ' - ', g.gadget_type) AS gadget_name, " +
        "r.repair_description AS problem, " +
        "a.username AS technician, " +
        "r.date_brought, " +
        "r.repair_status " +
        "FROM repairs r " +
        "JOIN gadgets g ON r.gadget_id = g.gadget_id " +
        "JOIN customers c ON g.customer_id = c.customer_id " +
        "LEFT JOIN technicians t ON r.technician_id = t.technician_id " +
        "LEFT JOIN accounts a ON t.account_id = a.account_id " +
        "WHERE r.technician_id = ? " +
        "AND r.is_archived = 0 " +
        "AND (" +
        "CONCAT(c.first_name, ' ', c.last_name) LIKE ? " +
        "OR g.brand_model LIKE ? " +
        "OR g.gadget_type LIKE ? " +
        "OR r.repair_description LIKE ?" +
        ") " +
        "ORDER BY r.repair_id DESC";

    try (
        Connection conn = DatabaseConnection.getConnection();
        PreparedStatement pst = conn.prepareStatement(sql)
    ) {

        String keyword = "%" + search + "%";

        // Technician ID
        pst.setInt(1, technicianId);

        // Search keyword
        pst.setString(2, keyword);
        pst.setString(3, keyword);
        pst.setString(4, keyword);
        pst.setString(5, keyword);

        try (ResultSet rs = pst.executeQuery()) {

            boolean found = false;

            while (rs.next()) {

                found = true;

                model.addRow(new Object[]{
                    rs.getInt("repair_id"),
                    rs.getString("customer_name"),
                    rs.getString("gadget_name"),
                    rs.getString("problem"),
                    rs.getString("technician"),
                    rs.getDate("date_brought"),
                    rs.getString("repair_status")
                });
            }

            if (!found) {

                JOptionPane.showMessageDialog(
                    this,
                    "No matching repair found."
                );

                loadRepairs();
            }
        }

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
            this,
            "Error searching repairs:\n" + e.getMessage(),
            "Database Error",
            JOptionPane.ERROR_MESSAGE
        );
    }// TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Technician1;
    private javax.swing.JLabel Technician2;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lblGreeting;
    private javax.swing.JTable tblRepairs;
    private javax.swing.JTextField txtSearchRepair;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
