/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gadgetrepair.frames.staff;
import gadgetrepair.frames.staff.DashboardFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import gadgetrepair.data.DatabaseConnection;
import gadgetrepair.frames.admin.AdminDashboardFrame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author User
 */
public class ArchivedCompletedRepairFrame extends javax.swing.JFrame {
    private String userRole;
    private String username;


    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ArchivedCompletedRepairFrame.class.getName());
    
    private void loadArchivedRepairs() {
  DefaultTableModel model =
        (DefaultTableModel) tblArchivedRepairs.getModel();

    model.setRowCount(0);

    String sql =
    "SELECT r.repair_id, " +
    "CONCAT(c.first_name, ' ', c.last_name) AS customer_name, " +
    "CONCAT(g.brand_model, ' - ', g.gadget_type) AS gadget_name, " +
    "r.repair_description, " +
    "a.username AS technician_name, " +
    "r.repair_status, " +
    "r.date_brought, " +
    "r.date_returned, " +
    "r.repair_cost " +
    "FROM repairs r " +
    "JOIN gadgets g ON r.gadget_id = g.gadget_id " +
    "JOIN customers c ON g.customer_id = c.customer_id " +
    "LEFT JOIN technicians t ON r.technician_id = t.technician_id " +
    "LEFT JOIN accounts a ON t.account_id = a.account_id " +
    "WHERE r.repair_status = 'Completed' " +
    "AND r.is_archived = 1";

    try (
        Connection conn = DatabaseConnection.getConnection();
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery()
    ) {

        while (rs.next()) {

            model.addRow(new Object[]{
       rs.getInt("repair_id"),
    rs.getString("customer_name"),
    rs.getString("gadget_name"),
    rs.getString("repair_description"),
    rs.getString("technician_name"),
    rs.getString("repair_status"),
    rs.getDate("date_brought"),
    rs.getDate("date_returned"),
    rs.getBigDecimal("repair_cost")
            });
        }

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
            this,
            "Error loading archived repairs:\n" + e.getMessage()
        );
    }
}
    
    
    
    public ArchivedCompletedRepairFrame(String userRole) {
    initComponents();
    this.userRole = userRole;
        loadArchivedRepairs();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTitle = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnRestore = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblArchivedRepairs = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(18, 52, 86));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 80));

        txtTitle.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(242, 242, 242));
        txtTitle.setText("ARCHIVED COMPLETED REPAIRS");
        txtTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\LOGO REPAIRsss.png")); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(135, 135));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTitle)
                .addGap(202, 202, 202)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTitle)
                .addGap(36, 36, 36))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("ARCHIVED CUSTOMER RECORDS ");

        jLabel2.setText("Search Customer:");

        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        btnRestore.setText("RESTORE");
        btnRestore.addActionListener(this::btnRestoreActionPerformed);

        btnBack.setBackground(new java.awt.Color(24, 91, 160));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.addActionListener(this::btnBackActionPerformed);

        tblArchivedRepairs.setBackground(new java.awt.Color(15, 43, 77));
        tblArchivedRepairs.setForeground(new java.awt.Color(255, 255, 255));
        tblArchivedRepairs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "REPAIR ID", "CUSTOMER", "GADGET", "PROBLEM", "REPAIR TECHNICIAN", "STATUS", "DATA BROUGHT", "DATE RETURNED", "REPAIR COST"
            }
        ));
        tblArchivedRepairs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblArchivedRepairsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblArchivedRepairs);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1254, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 994, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRestore)
                .addGap(128, 128, 128)
                .addComponent(btnBack)
                .addGap(208, 208, 208))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(71, 71, 71)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnRestore))
                .addContainerGap(388, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
         if (userRole.equalsIgnoreCase("admin")) {
        new AdminDashboardFrame(username).setVisible(true);
    } else {
        new DashboardFrame(username).setVisible(true);
    }

    this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void tblArchivedRepairsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblArchivedRepairsMouseClicked
    
        // TODO add your handling code here:
    }//GEN-LAST:event_tblArchivedRepairsMouseClicked

    private void btnRestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestoreActionPerformed
 int row = tblArchivedRepairs.getSelectedRow();

    if (row < 0) {
        JOptionPane.showMessageDialog(
            this,
            "Please select an archived repair first."
        );
        return;
    }

    int repairId = Integer.parseInt(
        tblArchivedRepairs.getValueAt(row, 0).toString()
    );

    int confirm = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to restore this repair?",
        "Confirm Restore",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    String sql =
        "UPDATE repairs " +
        "SET is_archived = 0 " +
        "WHERE repair_id = ?";

    try (
        Connection conn = DatabaseConnection.getConnection();
        PreparedStatement pst = conn.prepareStatement(sql)
    ) {

        pst.setInt(1, repairId);

        int updated = pst.executeUpdate();

        if (updated > 0) {

            JOptionPane.showMessageDialog(
                this,
                "Repair restored successfully!"
            );

            loadArchivedRepairs();

        } else {

            JOptionPane.showMessageDialog(
                this,
                "Repair was not found."
            );
        }

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
            this,
            "Error restoring repair:\n" + e.getMessage()
        );
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRestoreActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
 String search = txtSearch.getText().trim();

    if (search.isEmpty()) {
        JOptionPane.showMessageDialog(
            this,
            "Please enter a name, gadget, or problem."
        );
        return;
    }

    DefaultTableModel model =
        (DefaultTableModel) tblArchivedRepairs.getModel();

    model.setRowCount(0);

    String sql =
        "SELECT r.repair_id, " +
        "CONCAT(c.first_name, ' ', c.last_name) AS customer_name, " +
        "CONCAT(g.brand_model, ' - ', g.gadget_type) AS gadget_name, " +
        "r.repair_description, " +
        "a.username AS technician_name, " +
        "r.repair_status, " +
        "r.date_brought, " +
        "r.date_returned, " +
        "r.repair_cost " +
        "FROM repairs r " +
        "JOIN gadgets g ON r.gadget_id = g.gadget_id " +
        "JOIN customers c ON g.customer_id = c.customer_id " +
        "LEFT JOIN technicians t ON r.technician_id = t.technician_id " +
        "LEFT JOIN accounts a ON t.account_id = a.account_id " +
        "WHERE r.repair_status = 'Completed' " +
        "AND r.is_archived = 1 " +
        "AND (" +
        "CONCAT(c.first_name, ' ', c.last_name) LIKE ? OR " +
        "g.brand_model LIKE ? OR " +
        "g.gadget_type LIKE ? OR " +
        "r.repair_description LIKE ?" +
        ") " +
        "ORDER BY r.repair_id";

    try (
        Connection conn = DatabaseConnection.getConnection();
        PreparedStatement pst = conn.prepareStatement(sql)
    ) {

        pst.setString(1, "%" + search + "%");
        pst.setString(2, "%" + search + "%");
        pst.setString(3, "%" + search + "%");
        pst.setString(4, "%" + search + "%");

        try (ResultSet rs = pst.executeQuery()) {

            boolean found = false;

            while (rs.next()) {

                found = true;

                model.addRow(new Object[]{
                    rs.getInt("repair_id"),
                    rs.getString("customer_name"),
                    rs.getString("gadget_name"),
                    rs.getString("repair_description"),
                    rs.getString("technician_name"),
                    rs.getString("repair_status"),
                    rs.getDate("date_brought"),
                    rs.getDate("date_returned"),
                    rs.getBigDecimal("repair_cost")
                });
            }

            if (!found) {

                JOptionPane.showMessageDialog(
                    this,
                    "No matching archived repair found."
                );

                loadArchivedRepairs();
            }
        }

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
            this,
            "Error searching archived repairs:\n" +
            e.getMessage()
        );
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRestore;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblArchivedRepairs;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
