/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gadgetrepair.frames.staff;
import gadgetrepair.frames.staff.DashboardFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import gadgetrepair.data.DatabaseConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author User
 */
public class CompletedRepairFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CompletedRepairFrame.class.getName());
    private String username;

    private void loadCompletedRepairs() {

    DefaultTableModel model =
        (DefaultTableModel) tblCompletedRepairs.getModel();

    model.setRowCount(0);

    String sql =
        "SELECT " +
        "r.repair_id, " +
        "CONCAT(c.first_name, ' ', c.last_name) AS customer_name, " +
        "CONCAT(g.gadget_type, ' - ', g.brand_model) AS gadget_name, " +
        "r.repair_description, " +
        "a.username AS technician_name, " +
        "r.date_brought " +
        "FROM repairs r " +
        "JOIN gadgets g ON r.gadget_id = g.gadget_id " +
        "JOIN customers c ON g.customer_id = c.customer_id " +
        "LEFT JOIN technicians t ON r.technician_id = t.technician_id " +
        "LEFT JOIN accounts a ON t.account_id = a.account_id " +
        "WHERE r.repair_status = 'Completed' " +
        "AND r.is_archived = 0 " +
        "ORDER BY r.repair_id";

    try (
        Connection conn = DatabaseConnection.getConnection();
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery()
    ) {

        while (rs.next()) {

            model.addRow(new Object[]{
                rs.getInt("repair_id"),
                rs.getString("customer_name"),
                rs.getString("gadget_name"),
                rs.getString("repair_description"),
                rs.getString("technician_name"),
                rs.getDate("date_brought")
            });
        }

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
            this,
            "Error loading completed repairs:\n" + e.getMessage()
        );
    }
}
    private void clearRepairDetails() {

    lblRepairId.setText("-");
    lblCustomer.setText("-");
    lblGadget.setText("-");
    lblTechnician.setText("-");
    lblDateBrought.setText("-");
    lblDateBrought.setText("-");

    txtProblem.setText("");
    txtRepairCost.setText("");

    cldrDateReturned.setDate(null);
}
    public CompletedRepairFrame() {
        initComponents();
        loadCompletedRepairs();

    tblCompletedRepairs.setDefaultEditor(Object.class, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTitle = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblRepairId = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblCustomer = new javax.swing.JLabel();
        lblGadget = new javax.swing.JLabel();
        lblTechnician = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnGenerateReceipt = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        scrollCompletedRepairs = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompletedRepairs = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        cldrDateReturned = new com.toedter.calendar.JDateChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtProblem = new javax.swing.JTextArea();
        txtRepairCost = new javax.swing.JTextField();
        btnArchive = new javax.swing.JButton();
        lblDateBrought = new javax.swing.JLabel();
        btnSaveDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(18, 52, 86));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 80));

        txtTitle.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(242, 242, 242));
        txtTitle.setText("COMPLETED REPAIRS");
        txtTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\LOGO REPAIRsss.png")); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(135, 135));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(txtTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(txtTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setText("SEARCH :");

        txtSearch.addActionListener(this::txtSearchActionPerformed);

        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        jLabel4.setText("Repair ID:");

        lblRepairId.setBackground(new java.awt.Color(0, 153, 204));
        lblRepairId.setText("-");

        jLabel6.setText("Customer:");

        jLabel7.setText("Gadget:");

        jLabel9.setText("Technician:");

        jLabel10.setText("Problem:");

        jLabel11.setText("Date Brought");

        lblCustomer.setBackground(new java.awt.Color(0, 153, 204));
        lblCustomer.setText("-");

        lblGadget.setBackground(new java.awt.Color(0, 153, 204));
        lblGadget.setText("-");

        lblTechnician.setBackground(new java.awt.Color(0, 153, 204));
        lblTechnician.setText("-");

        jLabel17.setText("Date Returned:");

        jLabel18.setText("Repair Cost:");

        btnGenerateReceipt.setBackground(new java.awt.Color(24, 91, 160));
        btnGenerateReceipt.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerateReceipt.setText("GENERATE RECEIPT");
        btnGenerateReceipt.addActionListener(this::btnGenerateReceiptActionPerformed);

        btnBack.setBackground(new java.awt.Color(24, 91, 160));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.addActionListener(this::btnBackActionPerformed);

        tblCompletedRepairs.setBackground(new java.awt.Color(15, 43, 77));
        tblCompletedRepairs.setForeground(new java.awt.Color(255, 255, 255));
        tblCompletedRepairs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "REPAIR ID", "CUSTOMER", "GADGET", "PROBLEM", "REPAIR TECHNICIAN", "DATA BROUGHT"
            }
        ));
        tblCompletedRepairs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCompletedRepairsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCompletedRepairs);

        scrollCompletedRepairs.setViewportView(jScrollPane1);

        txtProblem.setEditable(false);
        txtProblem.setColumns(20);
        txtProblem.setRows(5);
        jScrollPane3.setViewportView(txtProblem);

        txtRepairCost.addActionListener(this::txtRepairCostActionPerformed);

        btnArchive.setBackground(new java.awt.Color(24, 91, 160));
        btnArchive.setForeground(new java.awt.Color(255, 255, 255));
        btnArchive.setText("ARCHIVE");
        btnArchive.addActionListener(this::btnArchiveActionPerformed);

        lblDateBrought.setBackground(new java.awt.Color(0, 153, 204));
        lblDateBrought.setText("-");

        btnSaveDetails.setBackground(new java.awt.Color(24, 91, 160));
        btnSaveDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveDetails.setText("SAVE DETAILS");
        btnSaveDetails.addActionListener(this::btnSaveDetailsActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollCompletedRepairs, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(23, 23, 23)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btnSearch)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel17))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblDateBrought, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 449, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblGadget, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblRepairId, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblTechnician, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cldrDateReturned, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel18)
                                        .addGap(38, 38, 38)
                                        .addComponent(txtRepairCost, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnSaveDetails)
                                        .addGap(39, 39, 39)
                                        .addComponent(btnArchive, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(btnGenerateReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15)))))
                        .addGap(143, 143, 143))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addComponent(scrollCompletedRepairs, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(lblRepairId)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblCustomer))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblGadget))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblTechnician))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblDateBrought))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(cldrDateReturned, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSaveDetails)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnArchive)
                                .addComponent(btnGenerateReceipt))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtRepairCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBack)))
                .addGap(173, 173, 173))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReceiptActionPerformed
 int row = tblCompletedRepairs.getSelectedRow();

if (row == -1) {
    JOptionPane.showMessageDialog(
        this,
        "Please select a completed repair first."
    );
    return;
}

String repairId =
    tblCompletedRepairs.getValueAt(row, 0).toString();

String customer =
    tblCompletedRepairs.getValueAt(row, 1).toString();

String gadget =
    tblCompletedRepairs.getValueAt(row, 2).toString();

String problem =
    tblCompletedRepairs.getValueAt(row, 3).toString();

String technician =
    tblCompletedRepairs.getValueAt(row, 4).toString();

String dateBrought =
    lblDateBrought.getText();

if (cldrDateReturned.getDate() == null) {
    JOptionPane.showMessageDialog(
        this,
        "Please select the date returned."
    );
    return;
}

java.text.SimpleDateFormat sdf =
    new java.text.SimpleDateFormat("yyyy-MM-dd");

String dateReturned =
    sdf.format(cldrDateReturned.getDate());

double repairCostValue;

try {
    repairCostValue =
        Double.parseDouble(txtRepairCost.getText().trim());
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(
        this,
        "Please enter a valid repair cost."
    );
    return;
}

String repairCost =
    String.format("₱%,.2f", repairCostValue);

if (repairCost.isEmpty()) {
    JOptionPane.showMessageDialog(
        this,
        "Please enter the repair cost."
    );
    return;
}

ReceiptDialog receipt = new ReceiptDialog(
    this,
    repairId,
    customer,
    gadget,
    problem,
    technician,
    dateBrought,
    dateReturned,
    repairCost
);

receipt.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerateReceiptActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnArchiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchiveActionPerformed
  int row = tblCompletedRepairs.getSelectedRow();

    if (row < 0) {
        JOptionPane.showMessageDialog(
            this,
            "Please select a completed repair first."
        );
        return;
    }

    int repairId = Integer.parseInt(
        tblCompletedRepairs.getValueAt(row, 0).toString()
    );

    int confirm = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to archive this completed repair?",
        "Confirm Archive",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    String sql =
        "UPDATE repairs " +
        "SET is_archived = 1 " +
        "WHERE repair_id = ?";

    try (
        Connection conn = DatabaseConnection.getConnection();
        PreparedStatement pst = conn.prepareStatement(sql)
    ) {

        pst.setInt(1, repairId);

        int updated = pst.executeUpdate();

        if (updated > 0) {

            JOptionPane.showMessageDialog(
                this,
                "Completed repair archived successfully!"
            );

            loadCompletedRepairs();

            clearRepairDetails();

        } else {

            JOptionPane.showMessageDialog(
                this,
                "Repair was not found."
            );
        }

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
            this,
            "Error archiving repair:\n" + e.getMessage()
        );
    }
       // TODO add your handling code here:
    }//GEN-LAST:event_btnArchiveActionPerformed

    private void tblCompletedRepairsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCompletedRepairsMouseClicked
    int row = tblCompletedRepairs.getSelectedRow();

    if (row < 0) {
        return;
    }

    int repairId = Integer.parseInt(
        tblCompletedRepairs.getValueAt(row, 0).toString()
    );

    String sql =
        "SELECT " +
        "r.repair_id, " +
        "CONCAT(c.first_name, ' ', c.last_name) AS customer_name, " +
        "CONCAT(g.gadget_type, ' - ', g.brand_model) AS gadget_name, " +
        "r.repair_description, " +
        "a.username AS technician_name, " +
        "r.date_brought, " +
        "r.date_returned, " +
        "r.repair_cost " +
        "FROM repairs r " +
        "JOIN gadgets g ON r.gadget_id = g.gadget_id " +
        "JOIN customers c ON g.customer_id = c.customer_id " +
        "LEFT JOIN technicians t ON r.technician_id = t.technician_id " +
        "LEFT JOIN accounts a ON t.account_id = a.account_id " +
        "WHERE r.repair_id = ?";

    try (
        Connection conn = DatabaseConnection.getConnection();
        PreparedStatement pst = conn.prepareStatement(sql)
    ) {

        pst.setInt(1, repairId);

        ResultSet rs = pst.executeQuery();

        if (rs.next()) {

            lblRepairId.setText(
                String.valueOf(rs.getInt("repair_id"))
            );

            lblCustomer.setText(
                rs.getString("customer_name")
            );

            lblGadget.setText(
                rs.getString("gadget_name")
            );

            lblTechnician.setText(
                rs.getString("technician_name")
            );

            txtProblem.setText(
                rs.getString("repair_description")
            );

            lblDateBrought.setText(
                String.valueOf(rs.getDate("date_brought"))
            );

            if (rs.getDate("date_returned") != null) {
                cldrDateReturned.setDate(
                    rs.getDate("date_returned")
                );
            } else {
                cldrDateReturned.setDate(null);
            }

            if (rs.getObject("repair_cost") != null) {
                txtRepairCost.setText(
                    rs.getBigDecimal("repair_cost").toString()
                );
            } else {
                txtRepairCost.setText("");
            }
        }

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
            this,
            "Error loading repair details:\n" + e.getMessage()
        );
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCompletedRepairsMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
  new DashboardFrame(username).setVisible(true);
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
 String search = txtSearch.getText().trim();

    if (search.isEmpty()) {
        loadCompletedRepairs();
        return;
    }

    DefaultTableModel model =
        (DefaultTableModel) tblCompletedRepairs.getModel();

    model.setRowCount(0);

    String sql =
        "SELECT " +
        "r.repair_id, " +
        "CONCAT(c.first_name, ' ', c.last_name) AS customer_name, " +
        "CONCAT(g.gadget_type, ' - ', g.brand_model) AS gadget_name, " +
        "r.repair_description, " +
        "a.username AS technician_name, " +
        "r.date_brought " +
        "FROM repairs r " +
        "JOIN gadgets g ON r.gadget_id = g.gadget_id " +
        "JOIN customers c ON g.customer_id = c.customer_id " +
        "LEFT JOIN technicians t ON r.technician_id = t.technician_id " +
        "LEFT JOIN accounts a ON t.account_id = a.account_id " +
        "WHERE r.repair_status = 'Completed' " +
        "AND r.is_archived = 0 " +
        "AND (" +
        "CONCAT(c.first_name, ' ', c.last_name) LIKE ? OR " +
        "g.gadget_type LIKE ? OR " +
        "g.brand_model LIKE ? OR " +
        "r.repair_description LIKE ?" +
        ") " +
        "ORDER BY r.repair_id DESC";

    try (
        Connection conn = DatabaseConnection.getConnection();
        PreparedStatement pst = conn.prepareStatement(sql)
    ) {

        String keyword = "%" + search + "%";

        pst.setString(1, keyword);
        pst.setString(2, keyword);
        pst.setString(3, keyword);
        pst.setString(4, keyword);

        try (ResultSet rs = pst.executeQuery()) {

            boolean found = false;

            while (rs.next()) {

                found = true;

                model.addRow(new Object[]{
                    rs.getInt("repair_id"),
                    rs.getString("customer_name"),
                    rs.getString("gadget_name"),
                    rs.getString("repair_description"),
                    rs.getString("technician_name"),
                    rs.getDate("date_brought")
                });
            }

            if (!found) {
                JOptionPane.showMessageDialog(
                    this,
                    "No matching completed repair found."
                );

                loadCompletedRepairs();
            }
        }

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
            this,
            "Error searching completed repairs:\n" + e.getMessage()
        );
    }       // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSaveDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDetailsActionPerformed
int row = tblCompletedRepairs.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(
            this,
            "Please select a completed repair first."
        );
        return;
    }

    // Get Repair ID from selected row
    int repairId = Integer.parseInt(
        tblCompletedRepairs.getValueAt(row, 0).toString()
    );

    // Check Date Returned
    if (cldrDateReturned.getDate() == null) {
        JOptionPane.showMessageDialog(
            this,
            "Please select the date returned."
        );
        return;
    }

    // Check Repair Cost
    String costText = txtRepairCost.getText().trim();

    if (costText.isEmpty()) {
        JOptionPane.showMessageDialog(
            this,
            "Please enter the repair cost."
        );
        return;
    }

    double repairCost;

    try {
        repairCost = Double.parseDouble(costText);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(
            this,
            "Please enter a valid repair cost."
        );
        return;
    }

    // Convert JDateChooser date to SQL Date
    java.sql.Date dateReturned =
        new java.sql.Date(
            cldrDateReturned.getDate().getTime()
        );

    String sql =
        "UPDATE repairs " +
        "SET date_returned = ?, repair_cost = ? " +
        "WHERE repair_id = ?";

    try (
        Connection conn = DatabaseConnection.getConnection();
        PreparedStatement pst = conn.prepareStatement(sql)
    ) {

        pst.setDate(1, dateReturned);
        pst.setDouble(2, repairCost);
        pst.setInt(3, repairId);

        int updated = pst.executeUpdate();

        if (updated > 0) {

            JOptionPane.showMessageDialog(
                this,
                "Repair details saved successfully!"
            );

            // Refresh the table
            loadCompletedRepairs();

        } else {

            JOptionPane.showMessageDialog(
                this,
                "Repair not found."
            );
        }

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
            this,
            "Error saving repair details:\n" + e.getMessage()
        );
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveDetailsActionPerformed

    private void txtRepairCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRepairCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRepairCostActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CompletedRepairFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArchive;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGenerateReceipt;
    private javax.swing.JButton btnSaveDetails;
    private javax.swing.JButton btnSearch;
    private com.toedter.calendar.JDateChooser cldrDateReturned;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblDateBrought;
    private javax.swing.JLabel lblGadget;
    private javax.swing.JLabel lblRepairId;
    private javax.swing.JLabel lblTechnician;
    private javax.swing.JScrollPane scrollCompletedRepairs;
    private javax.swing.JTable tblCompletedRepairs;
    private javax.swing.JTextArea txtProblem;
    private javax.swing.JTextField txtRepairCost;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
