
package gadgetrepair.frames.staff;
import gadgetrepair.frames.staff.DashboardFrame;
import gadgetrepair.data.DatabaseConnection;
import gadgetrepair.frames.admin.AdminDashboardFrame;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class GadgetFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(GadgetFrame.class.getName());

    private String userRole;
    private String username;

    public GadgetFrame(String userRole) {

        initComponents();

        this.userRole = userRole;

        // JTable cannot be edited directly
        tblGadgets.setDefaultEditor(Object.class, null);
        tblCustomerResults.setDefaultEditor(Object.class, null);

        // Make text areas look cleaner
        txtProblem.setLineWrap(true);
        txtProblem.setWrapStyleWord(true);

        // Gadget ID is generated by MySQL
        txtGadgetId.setEditable(false);

        // Selected customer information is display-only
        txtSelectedCustomerId.setEditable(false);
        txtSelectedCustomerName.setEditable(false);
        txtSelectedContact.setEditable(false);

        // Start with an empty gadget table
        refreshGadgetTable();
    }

    // =========================================================
    // LOAD ALL ACTIVE GADGETS
    // =========================================================

    private void refreshGadgetTable() {

        DefaultTableModel model =
                (DefaultTableModel) tblGadgets.getModel();

        model.setRowCount(0);

        String sql =
                "SELECT gadget_id, customer_id, " +
                "gadget_type, brand_model, problem " +
                "FROM gadgets " +
                "WHERE is_active = 1 " +
                "ORDER BY gadget_id";

        try (
                Connection conn = DatabaseConnection.getConnection();
                PreparedStatement pst = conn.prepareStatement(sql);
                ResultSet rs = pst.executeQuery()
        ) {

            while (rs.next()) {

                model.addRow(new Object[]{
                    rs.getInt("gadget_id"),
                    rs.getInt("customer_id"),
                    rs.getString("gadget_type"),
                    rs.getString("brand_model"),
                    rs.getString("problem")
                });
            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error loading gadgets:\n" + e.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    // =========================================================
    // CLEAR GADGET FORM
    // =========================================================

    private void clearGadgetForm() {

        txtGadgetId.setText("");

        txtSelectedCustomerId.setText("");
        txtSelectedCustomerName.setText("");
        txtSelectedContact.setText("");

        txtGadgetType.setText("");
        txtBrandModel.setText("");
        txtProblem.setText("");

        tblGadgets.clearSelection();
        tblCustomerResults.clearSelection();
    }

    // =========================================================
    // CLEAR CUSTOMER SEARCH RESULTS
    // =========================================================

    private void clearCustomerResults() {

        DefaultTableModel model =
                (DefaultTableModel) tblCustomerResults.getModel();

        model.setRowCount(0);
    }

      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtGadgetType = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBrandModel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        txtGadgetId = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtProblem = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtCustomerSearch = new javax.swing.JTextField();
        btnSearchCustomer = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblCustomerResults = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtSelectedCustomerId = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtSelectedCustomerName = new javax.swing.JTextField();
        txtSelectedContact = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        txtGadgetSearch = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGadgets = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 247, 250));

        jPanel1.setBackground(new java.awt.Color(18, 52, 86));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 85));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\LOGO REPAIRsss.png")); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(135, 135));

        txtTitle.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(242, 242, 242));
        txtTitle.setText("GADGET MANAGEMENT");
        txtTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTitle)
                .addGap(426, 426, 426)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(txtTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 230));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("GADGET INFORMATION");

        jLabel4.setText("Gadget Type:");

        jLabel2.setForeground(new java.awt.Color(30, 41, 59));
        jLabel2.setText("Gadget ID:");

        txtGadgetType.addActionListener(this::txtGadgetTypeActionPerformed);

        jLabel5.setText("Brand/Model:");

        txtBrandModel.addActionListener(this::txtBrandModelActionPerformed);

        jLabel6.setText("Problem:");

        btnAdd.setBackground(new java.awt.Color(24, 91, 160));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("ADD");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnEdit.setBackground(new java.awt.Color(24, 91, 160));
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("EDIT");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnSave.setBackground(new java.awt.Color(24, 91, 160));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("SAVE");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        txtGadgetId.setEditable(false);
        txtGadgetId.addActionListener(this::txtGadgetIdActionPerformed);

        txtProblem.setColumns(20);
        txtProblem.setRows(5);
        jScrollPane3.setViewportView(txtProblem);

        jLabel1.setText("Search Customer:");

        btnSearchCustomer.setText("Search");
        btnSearchCustomer.addActionListener(this::btnSearchCustomerActionPerformed);

        tblCustomerResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Customer ID", "Customer Name", "Contact Number"
            }
        ));
        tblCustomerResults.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomerResultsMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblCustomerResults);

        jScrollPane5.setViewportView(jScrollPane4);

        jLabel3.setText("Selected Customer");

        jLabel11.setText("Customer ID:");

        txtSelectedCustomerId.setEditable(false);
        txtSelectedCustomerId.addActionListener(this::txtSelectedCustomerIdActionPerformed);

        jLabel12.setText("Customer Name:");

        jLabel13.setText("Contact Number:");

        txtSelectedCustomerName.setEditable(false);
        txtSelectedCustomerName.addActionListener(this::txtSelectedCustomerNameActionPerformed);

        txtSelectedContact.setEditable(false);
        txtSelectedContact.addActionListener(this::txtSelectedContactActionPerformed);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel3.setPreferredSize(new java.awt.Dimension(550, 330));

        btnSearch.setBackground(new java.awt.Color(24, 91, 160));
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("GADGET RECORDS");

        jLabel7.setText("Search:");

        tblGadgets.setBackground(new java.awt.Color(15, 43, 77));
        tblGadgets.setForeground(new java.awt.Color(255, 255, 255));
        tblGadgets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Gadget ID", "Customer ID", "Type", "Brand/Model", "Problem"
            }
        ));
        tblGadgets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGadgetsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGadgets);

        jScrollPane2.setViewportView(jScrollPane1);

        btnBack.setBackground(new java.awt.Color(15, 43, 77));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtGadgetSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnSearch))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtGadgetSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtCustomerSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(btnSearchCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jScrollPane5)
                                    .addComponent(txtGadgetId)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(16, 16, 16)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtGadgetType, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtSelectedContact, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtBrandModel, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 2, Short.MAX_VALUE))
                                            .addComponent(jScrollPane3)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSelectedCustomerName))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSelectedCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel9))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGadgetId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCustomerSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchCustomer))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(txtSelectedCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(txtSelectedCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSelectedContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtGadgetType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtBrandModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(btnEdit)
                            .addComponent(btnSave))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1525, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
  if ("admin".equalsIgnoreCase(userRole)) {

            new AdminDashboardFrame(username).setVisible(true);

        } else {

            new DashboardFrame(username).setVisible(true);
        }

        this.dispose();
           
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtGadgetIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGadgetIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGadgetIdActionPerformed

    private void txtGadgetTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGadgetTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGadgetTypeActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed

        int row = tblGadgets.getSelectedRow();

        if (row < 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please select a gadget to edit."
            );

            return;
        }

        int gadgetId =
                Integer.parseInt(
                        tblGadgets.getValueAt(row, 0).toString()
                );

        int customerId =
                Integer.parseInt(
                        tblGadgets.getValueAt(row, 1).toString()
                );

        String gadgetType =
                tblGadgets.getValueAt(row, 2).toString();

        String brandModel =
                tblGadgets.getValueAt(row, 3).toString();

        String problem =
                tblGadgets.getValueAt(row, 4).toString();

        // Put gadget information into form
        txtGadgetId.setText(
                String.valueOf(gadgetId)
        );

        txtGadgetType.setText(gadgetType);
        txtBrandModel.setText(brandModel);
        txtProblem.setText(problem);

        // Load customer information
        loadCustomerInformation(customerId);
    }

    // =========================================================
    // LOAD CUSTOMER INFORMATION
    // =========================================================

    private void loadCustomerInformation(int customerId) {

        String sql =
                "SELECT first_name, last_name, contact_number " +
                "FROM customers " +
                "WHERE customer_id = ? " +
                "AND is_active = 1";

        try (
                Connection conn =
                        DatabaseConnection.getConnection();

                PreparedStatement pst =
                        conn.prepareStatement(sql)
        ) {

            pst.setInt(1, customerId);

            try (ResultSet rs = pst.executeQuery()) {

                if (rs.next()) {

                    String firstName =
                            rs.getString("first_name");

                    String lastName =
                            rs.getString("last_name");

                    String contact =
                            rs.getString("contact_number");

                    txtSelectedCustomerId.setText(
                            String.valueOf(customerId)
                    );

                    txtSelectedCustomerName.setText(
                            firstName + " " + lastName
                    );

                    txtSelectedContact.setText(contact);
                }
            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error loading customer:\n"
                    + e.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
       // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtBrandModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandModelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
  
        String customerIdText =
                txtSelectedCustomerId.getText().trim();

        String gadgetType =
                txtGadgetType.getText().trim();

        String brandModel =
                txtBrandModel.getText().trim();

        String problem =
                txtProblem.getText().trim();

        // Customer must be selected first
        if (customerIdText.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please search and select a customer first."
            );

            return;
        }

        // Gadget information must be complete
        if (gadgetType.isEmpty()
                || brandModel.isEmpty()
                || problem.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please complete all gadget fields."
            );

            return;
        }

        try {

            int customerId =
                    Integer.parseInt(customerIdText);

            String sql =
                    "INSERT INTO gadgets " +
                    "(customer_id, gadget_type, brand_model, problem, is_active) " +
                    "VALUES (?, ?, ?, ?, 1)";

            try (
                    Connection conn =
                            DatabaseConnection.getConnection();

                    PreparedStatement pst =
                            conn.prepareStatement(sql)
            ) {

                pst.setInt(1, customerId);
                pst.setString(2, gadgetType);
                pst.setString(3, brandModel);
                pst.setString(4, problem);

                pst.executeUpdate();
            }

            JOptionPane.showMessageDialog(
                    this,
                    "Gadget added successfully!"
            );

            refreshGadgetTable();

            clearGadgetForm();

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Invalid Customer ID."
            );

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error adding gadget:\n" + e.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }   // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void tblGadgetsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGadgetsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblGadgetsMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
  String search =
                txtGadgetSearch.getText().trim();

        DefaultTableModel model =
                (DefaultTableModel) tblGadgets.getModel();

        model.setRowCount(0);

        if (search.isEmpty()) {

            refreshGadgetTable();
            return;
        }

        String sql =
                "SELECT gadget_id, customer_id, " +
                "gadget_type, brand_model, problem " +
                "FROM gadgets " +
                "WHERE is_active = 1 " +
                "AND (" +
                "CAST(gadget_id AS CHAR) LIKE ? " +
                "OR CAST(customer_id AS CHAR) LIKE ? " +
                "OR gadget_type LIKE ? " +
                "OR brand_model LIKE ? " +
                "OR problem LIKE ?" +
                ") " +
                "ORDER BY gadget_id";

        try (
                Connection conn =
                        DatabaseConnection.getConnection();

                PreparedStatement pst =
                        conn.prepareStatement(sql)
        ) {

            String keyword =
                    "%" + search + "%";

            pst.setString(1, keyword);
            pst.setString(2, keyword);
            pst.setString(3, keyword);
            pst.setString(4, keyword);
            pst.setString(5, keyword);

            try (ResultSet rs = pst.executeQuery()) {

                boolean found = false;

                while (rs.next()) {

                    model.addRow(new Object[]{
                        rs.getInt("gadget_id"),
                        rs.getInt("customer_id"),
                        rs.getString("gadget_type"),
                        rs.getString("brand_model"),
                        rs.getString("problem")
                    });

                    found = true;
                }

                if (!found) {

                    JOptionPane.showMessageDialog(
                            this,
                            "Gadget not found."
                    );

                    refreshGadgetTable();
                }
            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error searching gadgets:\n"
                    + e.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
          // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
 
        String gadgetIdText =
                txtGadgetId.getText().trim();

        String customerIdText =
                txtSelectedCustomerId.getText().trim();

        String gadgetType =
                txtGadgetType.getText().trim();

        String brandModel =
                txtBrandModel.getText().trim();

        String problem =
                txtProblem.getText().trim();

        // Gadget ID is required when editing
        if (gadgetIdText.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please click EDIT on a gadget first."
            );

            return;
        }

        // Customer is required
        if (customerIdText.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please select a customer first."
            );

            return;
        }

        // Gadget information is required
        if (gadgetType.isEmpty()
                || brandModel.isEmpty()
                || problem.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please complete all gadget fields."
            );

            return;
        }

        try {

            int gadgetId =
                    Integer.parseInt(gadgetIdText);

            int customerId =
                    Integer.parseInt(customerIdText);

            String sql =
                    "UPDATE gadgets SET " +
                    "customer_id = ?, " +
                    "gadget_type = ?, " +
                    "brand_model = ?, " +
                    "problem = ? " +
                    "WHERE gadget_id = ? " +
                    "AND is_active = 1";

            try (
                    Connection conn =
                            DatabaseConnection.getConnection();

                    PreparedStatement pst =
                            conn.prepareStatement(sql)
            ) {

                pst.setInt(1, customerId);
                pst.setString(2, gadgetType);
                pst.setString(3, brandModel);
                pst.setString(4, problem);
                pst.setInt(5, gadgetId);

                int rowsUpdated =
                        pst.executeUpdate();

                if (rowsUpdated == 0) {

                    JOptionPane.showMessageDialog(
                            this,
                            "Gadget could not be updated."
                    );

                    return;
                }
            }

            JOptionPane.showMessageDialog(
                    this,
                    "Gadget updated successfully!"
            );

            refreshGadgetTable();

            clearGadgetForm();

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Invalid ID."
            );

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error updating gadget:\n"
                    + e.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    
     // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tblCustomerResultsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomerResultsMouseClicked
 int row = tblCustomerResults.getSelectedRow();

    if (row < 0) {
        return;
    }

    String customerId =
            tblCustomerResults.getValueAt(row, 0).toString();

    String customerName =
            tblCustomerResults.getValueAt(row, 1).toString();

    String contactNumber =
            tblCustomerResults.getValueAt(row, 2).toString();

    txtSelectedCustomerId.setText(customerId);
    txtSelectedCustomerName.setText(customerName);
    txtSelectedContact.setText(contactNumber);
    

   
// TODO add your handling code here:
    }//GEN-LAST:event_tblCustomerResultsMouseClicked

    private void btnSearchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCustomerActionPerformed
  String search =
            txtCustomerSearch.getText().trim();

    DefaultTableModel model =
            (DefaultTableModel) tblCustomerResults.getModel();

    model.setRowCount(0);

    if (search.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Please enter a Customer ID, name, or contact number."
        );

        return;
    }

    String sql =
            "SELECT customer_id, first_name, " +
            "last_name, contact_number " +
            "FROM customers " +
            "WHERE is_active = 1 " +
            "AND (" +
            "CAST(customer_id AS CHAR) LIKE ? " +
            "OR first_name LIKE ? " +
            "OR last_name LIKE ? " +
            "OR contact_number LIKE ?" +
            ") " +
            "ORDER BY customer_id";

    try (
            Connection conn = DatabaseConnection.getConnection();
            PreparedStatement pst = conn.prepareStatement(sql)
    ) {

        String keyword = "%" + search + "%";

        pst.setString(1, keyword);
        pst.setString(2, keyword);
        pst.setString(3, keyword);
        pst.setString(4, keyword);

        try (ResultSet rs = pst.executeQuery()) {

            boolean found = false;

            while (rs.next()) {

                String fullName =
                        rs.getString("first_name")
                        + " "
                        + rs.getString("last_name");

                model.addRow(new Object[]{
                    rs.getInt("customer_id"),
                    fullName,
                    rs.getString("contact_number")
                });

                found = true;
            }

            if (!found) {

                JOptionPane.showMessageDialog(
                        this,
                        "Customer not found."
                );
            }
        }

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
                this,
                "Error searching customer:\n"
                + e.getMessage(),
                "Database Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchCustomerActionPerformed

    private void txtSelectedCustomerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSelectedCustomerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSelectedCustomerIdActionPerformed

    private void txtSelectedCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSelectedCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSelectedCustomerNameActionPerformed

    private void txtSelectedContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSelectedContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSelectedContactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchCustomer;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblCustomerResults;
    private javax.swing.JTable tblGadgets;
    private javax.swing.JTextField txtBrandModel;
    private javax.swing.JTextField txtCustomerSearch;
    private javax.swing.JTextField txtGadgetId;
    private javax.swing.JTextField txtGadgetSearch;
    private javax.swing.JTextField txtGadgetType;
    private javax.swing.JTextArea txtProblem;
    private javax.swing.JTextField txtSelectedContact;
    private javax.swing.JTextField txtSelectedCustomerId;
    private javax.swing.JTextField txtSelectedCustomerName;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
